//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDatPhong
    {
        public PhieuDatPhong()
        {
            this.ChiTietPhieuDatPhongs = new HashSet<ChiTietPhieuDatPhong>();
        }
    
        public string MaPDP { get; set; }
        public string MaKH { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual ICollection<ChiTietPhieuDatPhong> ChiTietPhieuDatPhongs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
